config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  get 'welcome/info'
  get 'welcome/start'

  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
    unauthenticated { root 'welcome#index', as: :unauthenticated_root }
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :welcome, only: %i[index info start]
  resources :users, only: %i[show income update destroy]

  resources :groups, only: %i[index show new create destroy] do
    resources :entities, only: %i[index show new create destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :description, length: { maximum: 100 }

  after_save :update_groups_total_amount
  after_save :update_users_total_expenses
  after_destroy :update_users_total_expenses
  after_destroy :update_groups_total_amount

  private

  def update_groups_total_amount
    group = self.group
    group.total_amount = group.entities.sum(:amount)
    group.save
  end

  def update_users_total_expenses
    current_user = user
    current_user.total_expenses = current_user.entities.sum(:amount)
    current_user.save
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :entities, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :groups, dependent: :destroy
  has_many :entities, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_user, :logged_in?

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:error] = 'You must be logged in to access this section'
    redirect_to user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name income avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name income avatar])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :require_user

  def index
    @entities = current_user.entities.where(group_id: params[:group_id]).order(created_at: :desc)
    @group = Group.find(params[:group_id])
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.user = current_user
    @entity.group = Group.find(params[:group_id])
    if @entity.save
      flash[:success] = 'Entity was successfully created.'
      redirect_to group_entities_path
    else
      flash[:error] = 'Entity was not created.'
      render 'new'
    end
  end

  def destroy
    @entity = Entity.find(params[:id])
    @entity.destroy
    flash[:success] = 'Entity was successfully deleted.'
    redirect_to group_entities_path(@entity.group)
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :description)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user
  before_action :require_current_user, only: %i[edit update destroy]

  def index
    @groups = Group.where(user_id: current_user.id).order(created_at: :desc)
    @entities = current_user.entities.where(group_id: params[:group_id]).order(created_at: :desc)
    current_user.total_expenses = current_user.entities.sum(:amount).round(2)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      flash[:success] = 'Group was successfully created.'
      redirect_to groups_path
    else
      flash[:error] = 'Group was not created.'
      render 'new'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:success] = 'Group was successfully deleted.'
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :color)
  end

  def require_current_user
    @group = Group.find(params[:id])
    if @group.user_id == current_user.id
      true
    else
      flash[:error] = 'You are not authorized to perform this action.'
      redirect_to groups_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to groups_path if logged_in?
  end

  def info
    redirect_to groups_path if logged_in?
  end

  def start
    redirect_to groups_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    user.avatar.attached? ? user.avatar.variant(resize: '300x300') : 'https://www.w3schools.com/howto/img_avatar.png'
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entities/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="DeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Delete entity</h5>
        <ion-icon name="arrow-back" class="settings-button" data-dismiss="modal" aria-label="Close"></ion-icon>
      </div>
      <div class="modal-body">
        <% @entities.each do |entity| %>
        <li class="item">
          <div class="transaction-name">
            <%= link_to group_entity_path(@group, entity), method: :delete do %>
            <ion-icon name="trash-outline" class="transaction-img <%= @group.icon %>" data-toggle="modal" data-target="#DeleteModal"></ion-icon>
            <% end %>
            <p class="transaction-name__text"><%= entity.name %></p>
          </div>
          <div class="transaction-amount">
            <p class="transaction-amount__text">-$<%= entity.amount %></p>
          </div>
        </li>
        <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/entities/index.html.erb
<section class="details">
  <div class="details-title">
    <%= link_to groups_path do %>
    <ion-icon name="arrow-back" class="settings-button"></ion-icon>
    <% end %>
    <h1 class="details-title__text">Transactions</h1>
    <ion-icon name="options" class="settings-button"></ion-icon>
  </div>
  <div class="selections">
    <button type="button" class="selection income">
      <!-- delete group -->
      <%= link_to group_path(@group), method: :delete do %> Delete Group <% end %>
    </button>
    <button type="button" class="selection expenses" data-toggle="modal" data-target="#DeleteModal">Expenses</button>
  </div>
  <div class="tranactions">
    <div class="title">
      <p class="title__date"><% if @group.entities.present? %> <%= @group.entities.last.created_at.strftime("%b %d %Y") %> <% else %> <%= "No Entity added yet" %> <% end %></p>
      <p class="view-all">-<%= @group.total_amount %></p>
    </div>
    <ul class="transactions-list">
      <%= render 'modal' %> <% @entities.each do |entity| %>
      <li class="item">
        <div class="transaction-name">
          <ion-icon name="<%= @group.icon %>" class="transaction-img <%= @group.icon %>"></ion-icon>
          <p class="transaction-name__text"><%= entity.name.split(" ").map(&:capitalize).join(" ") %></p>
        </div>
        <div class="transaction-amount">
          <p class="transaction-amount__text">-$<%= entity.amount %></p>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="options">
    <%= link_to new_group_entity_path do %>
    <ion-icon name="add-outline" class="add-button"></ion-icon>
    <% end %>
  </div>
</section>

app/views/entities/new.html.erb
<% if @entity.errors.any? %>
<div class="alert alert-danger">
  <ul>
    <% @entity.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %> <%= form_for(@entity, :url => group_entities_path, :html => { :method => :post }) do |f| %>

<section class="add-expenses">
  <div class="add__amount">
    <div class="add__title">Add Group</div>
    <%= f.number_field :amount, :placeholder => "Amount", :class => "add__amount-input", :id => "amount", :placeholder => "$0", :min => 0, :step => 0.01 %>
    <div class="add__option category-title">
      <ion-icon name="clipboard-outline"></ion-icon>
      <%= f.text_field :name, :placeholder => "Name", :class => "option-text", maxlength: 20 %>
    </div>
    <div class="add__option category-title">
      <ion-icon name="calendar-outline"></ion-icon>
      <%= f.date_field :date, :class => "option-text" %>
    </div>
  </div>
  <div class="add__button"><%= button_to "Save", group_entities_path, :method => :post, :class => "add__save" %></div>
  <br />
  <% end %> <%= link_to group_entities_path, class: 'back__button' do %>
  <ion-icon name="arrow-back" class="settings-button"></ion-icon>
  <% end %>
</section>

app/views/groups/_groups.html.erb
<!-- Modal -->
<div class="modal fade" id="deleteGroup" tabindex="-1" role="dialog" aria-labelledby="deleteGroup" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Delete Group</h5>
        <ion-icon name="arrow-back" class="settings-button" data-dismiss="modal" aria-label="Close"></ion-icon>
      </div>
      <div class="modal-body">
        <% @groups.each do |group| %>
        <li class="item">
          <div class="transaction-name">
            <!-- link to delete group -->
            <%= link_to group_path(group), method: :delete do %> <ion-icon name="trash-outline" class="transaction-img <%= group.icon %>" data-toggle="modal" data-target="#DeleteModal"></ion-icon>
            <% end %>
            <p class="transaction-name__text"><%= group.name %></p>
          </div>
          <div class="transaction-amount">
            <p class="transaction-amount__text">-$<%= group.total_amount %></p>
          </div>
        </li>
        <br />
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_logout.html.erb
<!-- Modal -->
<div class="modal fade" id="LogOut" tabindex="-1" role="dialog" aria-labelledby="LogOut" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><%= current_user.name %> info</h5>
        <ion-icon name="arrow-back" class="settings-button" data-dismiss="modal" aria-label="Close"></ion-icon>
      </div>
      <div class="modal-body">If you log out, you will be logged out of all your devices. 
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-danger'%></div>
    </div>
  </div>
</div>

app/views/groups/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Budget App Info</h5>
        <ion-icon name="arrow-back" class="settings-button" data-dismiss="modal" aria-label="Close"></ion-icon>
      </div>
      <div class="modal-body">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime, consequuntur! Earum optio a officia officiis. Amet, officiis, eveniet ex magni necessitatibus fugit facilis vero delectus obcaecati ab eius libero! Nemo.</div>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<!-- display group name -->
<section class="home">
  <div class="user-container">
    <div class="user-info">
      <%= image_tag avatar_url(current_user), :class => "avatar" %>

      <div class="user-text">
        <p class="user-text__welcome">Welcome!</p>
        <p class="user-text__name"><%= current_user.name %></p>
      </div>
    </div>

    <!-- render modal -->
    <%= render 'modal' %> <%= render 'logout' %> <%= render 'groups' %>

    <!-- link to devise user edit -->
    <%= link_to edit_user_registration_path do %>
    <ion-icon name="settings" class="settings-button"></ion-icon>
    <% end %>
  </div>

  <div class="credit-card">
    <div class="credit-card__top">
      <div class="credit-card__top">
        <p class="credit-card__top__text">Total Expenses</p>
        <p class="credit-card__top__amount">$ <% if current_user.entities.present? %> <%= current_user.total_expenses.to_s.gsub(/\d(?=(\d{3})+\.)/, '\&,') %>.00 <% else %> 0.00 <% end %></p>
      </div>
    </div>
    <div class="credit-card__bottom">
      <div class="bottom-container">
        <ion-icon name="arrow-down-outline" class="income arrow"></ion-icon>
        <div class="info">
          <p class="bottom__text most">Most</p>
          <p class="bottom__amount">$ <% if current_user.entities.present? %> <%= current_user.entities.select { |entity| entity.amount == current_user.entities.max_by(&:amount).amount }.first.amount %>.00 <% else %> 0.00 <% end %></p>
        </div>
      </div>
      <div class="bottom-container">
        <ion-icon name="arrow-up-outline" class="expenses arrow"></ion-icon>
        <div class="info">
          <p class="bottom__text last">Last</p>
          <p class="bottom__amount"><% if current_user.entities.present? %> $ <%= current_user.entities.select { |entity| entity.amount == current_user.entities.min_by(&:amount).amount }.first.amount %><% else %> $ 0<% end %>.00</p>
        </div>
      </div>
    </div>
  </div>

  <div class="tranactions">
    <div class="title">
      <p class="title__text">Transactions</p>
      <p class="view-all" data-toggle="modal" data-target="#deleteGroup">View All</p>
    </div>
    <ul class="transactions-list">
      <% @groups.each do |group| %>

      <li class="item">
        <div class="transaction-name">
          <%= link_to group_entities_path(group) do %>
          <ion-icon name="<%= group.icon %>" class="transaction-img <%= group.icon %>"></ion-icon>
          <% end %>
          <p class="transaction-name__text"><%= link_to group.name.split(" ").map(&:capitalize).join(" "), group_entities_path(group) %></p>
        </div>
        <div class="transaction-amount">
          <p class="transaction-amount__text"><% if group.entities.present? %> -$<%= group.total_amount.to_s.gsub(/\d(?=(\d{3})+\.)/, '\&,') %>.00 <% else %> $ 0.00 <% end %></p>
          <p class="transaction-amount__date"><%= group.created_at.strftime("%a") %></p>
        </div>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="options">
    <ion-icon name="grid" class="menu-button" data-toggle="modal" data-target="#LogOut"></ion-icon>
    <%= link_to new_group_path do %>
    <ion-icon name="add-outline" class="add-button">Add</ion-icon>
    <% end %>
    <ion-icon name="alert-circle" class="show-button" data-toggle="modal" data-target="#exampleModal"></ion-icon>
  </div>
</section>

app/views/groups/new.html.erb
<% if @group.errors.any? %>
<div class="alert alert-danger">
  <ul>
    <% @group.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %> <%= form_for(@group, :url => groups_path, :html => { :method => :post }) do |f| %>

<section class="add-expenses">
  <div class="add__amount">
    <div class="add__title">Add Group</div>
    <div class="add__option category-title">
      <ion-icon name="clipboard-outline"></ion-icon>
      <%= f.text_field :name, :placeholder => "Name", :class => "option-text" %>
    </div>

    <div class="add__option category">
      <div class="category-title">
        <ion-icon name="options"></ion-icon>
        <p class="option-category">Category</p>
      </div>
      <div class="icons">
        <%= f.radio_button :icon, "fast-food-outline" %> <%= f.label :icon, class: "fast-food-outline", :value => "fast-food-outline" do%>
        <ion-icon name="fast-food-outline" class="transaction-img food" value="fast-food-outline"></ion-icon>
        <% end %> <%= f.radio_button :icon, "bag" %> <%= f.label :icon, :value => "bag" do%>
        <ion-icon name="bag" class="transaction-img bag" value="bag"></ion-icon>
        <% end %> <%= f.radio_button :icon, "ticket" %> <%= f.label :icon, :value => "ticket" do%>
        <ion-icon name="ticket" class="transaction-img ticket" value="ticket"></ion-icon>
        <% end %> <%= f.radio_button :icon, "airplane" %> <%= f.label :icon, :value => "airplane" do%>
        <ion-icon name="airplane" class="transaction-img airplane" value="airplane"></ion-icon>
        <% end %> <%= f.radio_button :icon, "barbell" %> <%= f.label :icon, :value => "barbell" do%>
        <ion-icon name="barbell" class="transaction-img barbell" value="barbell"></ion-icon>
        <% end %>
        <!-- car -->
        <%= f.radio_button :icon, "car" %> <%= f.label :icon, :value => "car" do%>
        <ion-icon name="car" class="transaction-img car" value="car"></ion-icon>
        <% end %>
        <!-- call -->
        <%= f.radio_button :icon, "call" %> <%= f.label :icon, :value => "call" do%>
        <ion-icon name="call" class="transaction-img call" value="call"></ion-icon>
        <% end %>
        <!-- bus -->
        <%= f.radio_button :icon, "bus" %> <%= f.label :icon, :value => "bus" do%>
        <ion-icon name="bus" class="transaction-img bus" value="bus"></ion-icon>
        <% end %>
        <!-- game-controller -->
        <%= f.radio_button :icon, "game-controller" %> <%= f.label :icon, :value => "game-controller" do%>
        <ion-icon name="game-controller" class="transaction-img game-controller" value="game-controller"></ion-icon>
        <% end %>
        <!-- home -->
        <%= f.radio_button :icon, "home" %> <%= f.label :icon, :value => "home" do%>
        <ion-icon name="home" class="transaction-img house" value="home"></ion-icon>
        <% end %>
        <!-- shirt -->
        <%= f.radio_button :icon, "shirt" %> <%= f.label :icon, :value => "shirt" do%>
        <ion-icon name="shirt" class="transaction-img shirt" value="shirt"></ion-icon>
        <% end %>
        <!-- bandage -->
        <%= f.radio_button :icon, "bandage" %> <%= f.label :icon, :value => "bandage" do%>
        <ion-icon name="bandage" class="transaction-img bandage" value="bandage"></ion-icon>
        <% end %>
      </div>
    </div>
  </div>
  <div class="add__button"><%= button_to "Save", groups_path, :method => :post, :class => "add__save" %></div>
  <% end %> <%= link_to groups_path, class: 'back__button' do %>
  <ion-icon name="arrow-back" class="settings-button"></ion-icon>
  <% end %>
</section>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %> <%= content_tag :div, msg, class: "alert alert-#{name}" %> <% end %>

<!-- style errors as flash -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
     <%= yield %>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/welcome/index.html.erb
<section class="welcome">
  <h1 class="welcome__title">Budget Planner</h1>
  <div class="welcome-image"><%= image_tag 'Wallet-amico.svg', class: 'welcome-illustration' %></div>
  <div class="welcome-text">
    <h2 class="welcome-text__title">Welcome to personal budget planner</h2>
    <p class="welcome-text__description">This is a mobile application that allows you to keep track of your expenses and incomes.</p>
  </div>
</section>
<div class="slide">
  <% if current_user.present? %>
  <%= link_to 'Skip', groups_path, class: 'skip__link' %>
  <% else %>
  <%= link_to 'Skip', new_user_session_path, class: 'skip__link' %>
  <% end %>
  <div class="dots">
    <span> . </span>
    <span> . </span>
    <span> . </span>
  </div>
  <%= link_to 'Next', welcome_info_path, class: 'next__link' %>
</div>

app/views/welcome/info.html.erb
<section class="welcome">
  <h1 class="welcome__title">Budget Planner</h1>
  <div class="welcome-image"><%= image_tag 'Wallet-bro.svg', class: 'welcome-illustration' %></div>
  <div class="welcome-text">
    <h2 class="welcome-text__title">Save money with us</h2>
    <p class="welcome-text__description">Easily create budgets, and see our suggestions based on your spending.</p>
  </div>
</section>
<div class="slide">
    <% if current_user.present? %>
  <%= link_to 'Skip', groups_path, class: 'skip__link' %>
  <% else %>
  <%= link_to 'Skip', new_user_session_path, class: 'skip__link' %>
  <% end %>
  <div class="dots">
    <span> . </span>
    <span> . </span>
    <span> . </span>
  </div>
  <%= link_to 'Next', welcome_start_path, class: 'next__link' %>
</div>

app/views/welcome/start.html.erb
<section class="welcome">
  <h1 class="welcome__title">Budget Planner</h1>
  <div class="welcome-image"><%= image_tag 'Wallet-cuate.svg', class: 'welcome-illustration' %></div>
  <div class="welcome-text">
    <h2 class="welcome-text__title">Track your bills like never before</h2>
    <p class="welcome-text__description">Builds a personal budget, based on your spending habits and preferences.</p>
  </div>
</section>
<div class="get-started"><%= button_to 'Get Started', user_session_path, class: 'add__save' %></div>